version: '3'

services:
  web:
    container_name: datadog.pdi.web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    command: [ "yarn", "dev" ]
    tty: true
    ports:
      - "3000:3000"
    environment:
      - DD_ENV=development
      - DD_HOST=datadog # this is the name of the datadog container
      - DD_LOGS_INJECTION=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - NODE_OPTIONS=-r dd-trace/init
      - NODE_ENV=development
    volumes:
      - ./web:/app
      - web/node_modules
    depends_on:
      - api
  api:
    container_name: datadog.pdi.api
    build:
      context: ./api
      dockerfile: Dockerfile
    command: yarn start:dev
    tty: true
    ports:
      - "3333:3333"
    environment:
      - DD_ENV=development
      - DD_HOST=datadog # this is the name of the datadog container
      - DD_LOGS_INJECTION=true
      - DD_APPSEC_ENABLED=true
    volumes:
      - ./api:/usr/src/app
      - api/node_modules
    depends_on:
      - postgres
  postgres:
    container_name: datadog.pdi.postgres
    image: postgres
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DD_ENV=development
    ports:
      - "5555:5432"
    depends_on:
      - datadog
    labels:
      com.datadoghq.ad.check_names: '["postgres"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port":5432,"username":"datadog","password":"datadog"}]'
      com.datadoghq.ad.logs: >-
        [{
          "source": "postgresql",
          "service": "datadog.pdi.postgres",
          "log_processing_rules": [{
            "type": "multi_line",
            "name": "log_start_with_date",
            "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"
          }]
        }]
  datadog:
    container_name: datadog.pdi.datadog
    build: datadog
    pid: host
    tty: true
    env_file:
      - datadog.env
    environment:
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  db_data:
    driver: local
