version: '3'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "3001:3001"
    environment:
      - DD_ENV=development
      - DD_HOST=datadog # this is the name of the datadog container
      - DD_LOGS_INJECTION=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - NODE_OPTIONS=-r dd-trace/init
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: yarn start:dev
    ports:
      - "3000:3000"
    environment:
      - DD_ENV=development
      - DD_HOST=datadog # this is the name of the datadog container
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
  postgres:
    image: postgres
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DD_ENV=development
    ports:
      - "5555:5432"
    depends_on:
      - datadog
    labels:
      com.datadoghq.ad.check_names: '["postgres"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port":5432,"username":"datadog","password":"datadog"}]'
      com.datadoghq.ad.logs: '[{"source":"postgresql","service":"postgresql"}]'
  datadog:
    build: datadog
    pid: host
    env_file:
      - datadog.env
    depends_on:
      - postgres
    environment:
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

volumes:
  db_data:
    driver: local
